"""Initial migration

Revision ID: 9a16bcc274bb
Revises: 
Create Date: 2025-12-18 17:41:41.019062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a16bcc274bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('difficulty_at_time', sa.String(length=16), nullable=True),
    sa.Column('emotion_at_time', sa.String(length=32), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_logs_answered_at'), 'answer_logs', ['answered_at'], unique=False)
    op.create_index(op.f('ix_answer_logs_question_id'), 'answer_logs', ['question_id'], unique=False)
    op.create_index(op.f('ix_answer_logs_user_id'), 'answer_logs', ['user_id'], unique=False)
    op.add_column('emotion_logs', sa.Column('context', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_emotion_logs_emotion'), 'emotion_logs', ['emotion'], unique=False)
    op.create_index(op.f('ix_emotion_logs_timestamp'), 'emotion_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_emotion_logs_user_id'), 'emotion_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('emotion_logs_user_id_fkey'), 'emotion_logs', type_='foreignkey')
    op.create_foreign_key(None, 'emotion_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('subject_performance', sa.Column('best_streak', sa.Integer(), nullable=False))
    op.add_column('subject_performance', sa.Column('total_time_spent', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_subject_performance_subject'), 'subject_performance', ['subject'], unique=False)
    op.create_index(op.f('ix_subject_performance_user_id'), 'subject_performance', ['user_id'], unique=False)
    op.create_unique_constraint('uix_user_subject_perf', 'subject_performance', ['user_id', 'subject'])
    op.drop_constraint(op.f('subject_performance_user_id_fkey'), 'subject_performance', type_='foreignkey')
    op.create_foreign_key(None, 'subject_performance', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('test_results', sa.Column('average_time_per_question', sa.Float(), nullable=True))
    op.create_index(op.f('ix_test_results_subject'), 'test_results', ['subject'], unique=False)
    op.create_index(op.f('ix_test_results_user_id'), 'test_results', ['user_id'], unique=False)
    op.drop_constraint(op.f('test_results_user_id_fkey'), 'test_results', type_='foreignkey')
    op.create_foreign_key(None, 'test_results', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_progress', sa.Column('current_difficulty', sa.String(length=16), nullable=False))
    op.create_index(op.f('ix_user_progress_subject'), 'user_progress', ['subject'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_unique_constraint('uix_user_subject', 'user_progress', ['user_id', 'subject'])
    op.drop_constraint(op.f('user_progress_user_id_fkey'), 'user_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'is_verified')
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.create_foreign_key(op.f('user_progress_user_id_fkey'), 'user_progress', 'users', ['user_id'], ['id'])
    op.drop_constraint('uix_user_subject', 'user_progress', type_='unique')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_subject'), table_name='user_progress')
    op.drop_column('user_progress', 'current_difficulty')
    op.drop_constraint(None, 'test_results', type_='foreignkey')
    op.create_foreign_key(op.f('test_results_user_id_fkey'), 'test_results', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_test_results_user_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_subject'), table_name='test_results')
    op.drop_column('test_results', 'average_time_per_question')
    op.drop_constraint(None, 'subject_performance', type_='foreignkey')
    op.create_foreign_key(op.f('subject_performance_user_id_fkey'), 'subject_performance', 'users', ['user_id'], ['id'])
    op.drop_constraint('uix_user_subject_perf', 'subject_performance', type_='unique')
    op.drop_index(op.f('ix_subject_performance_user_id'), table_name='subject_performance')
    op.drop_index(op.f('ix_subject_performance_subject'), table_name='subject_performance')
    op.drop_column('subject_performance', 'total_time_spent')
    op.drop_column('subject_performance', 'best_streak')
    op.drop_column('questions', 'created_at')
    op.drop_column('questions', 'explanation')
    op.drop_constraint(None, 'emotion_logs', type_='foreignkey')
    op.create_foreign_key(op.f('emotion_logs_user_id_fkey'), 'emotion_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_emotion_logs_user_id'), table_name='emotion_logs')
    op.drop_index(op.f('ix_emotion_logs_timestamp'), table_name='emotion_logs')
    op.drop_index(op.f('ix_emotion_logs_emotion'), table_name='emotion_logs')
    op.drop_column('emotion_logs', 'context')
    op.drop_index(op.f('ix_answer_logs_user_id'), table_name='answer_logs')
    op.drop_index(op.f('ix_answer_logs_question_id'), table_name='answer_logs')
    op.drop_index(op.f('ix_answer_logs_answered_at'), table_name='answer_logs')
    op.drop_table('answer_logs')
    # ### end Alembic commands ###
